DELETE http://localhost:3003/api/blogs/63e8ac7aac03eba1da8a38f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiYyIsImlkIjoiNjNlN2MzNWQ5ZDY2NWVkMDdhMzBkMjMwIiwiaWF0IjoxNjc2MjE3MDkwLCJleHAiOjE2NzYyMjA2OTB9.xC4bgvLPG4zZGTKx3AO1NQRZ1wrYMtU8pIE28b2o1LA