POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Julius Caesar >:(",
    "author": "Brutus",
    "url": "blog.brutus.org",
    "likes": 1,
    "userId": "63e661e37efaa798f1b4239b"
}
